version: "3"
services:
  app:
    container_name: app
    build: .
    command: node app.js
    ports:
      - "8080:8080"
    links:
      - "mongo:mongosrv"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=FramedEmeraldItem
      - MONGO_INITDB_ROOT_PASSWORD=ShineBrightLike4Diamond